server:
  port: ${SERVER_PORT}
spring:
  data:
    mongodb:
      uri: 'mongodb+srv://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/mongo-account-reactive-api?retryWrites=true&w=majority'

###### RESILIENCE4J CIRCUIT-BREAKER ###########
resilience4j:
  circuitbreaker:
    instances:
      createPartnerAccount:
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 25

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


integration:
  partner:
    url: ${PARTNER_URL}
    port: ${PARTNER_PORT}
